language: go
go:
- '1.0'
- '1.3'
deploy:
  provider: releases
  api_key:
    secure: H4gKcKZutAqcBVsPfHg8ssL7rsBU1CgYSHXk0Btt58qnI8e8kwD6wbu0P7ZrGXGCciPU5f/IW6XXlkzuwQLjUiSuirQRVixxCJwH07LRY/xsY3vTs2rC5EW/mDVsmHq1liBaLarRddScAdsLq1z/ZTKxzYJcR2IpP/KtctV8oFGLwxBVgEW3wRFgIMMwROgooToUOvwW5OhBKl1sHCcSueWgLYrezs1CtWyNLngo2oxnFVF/vqCsKktKKhqP35MbEa2RNsdIGvSt24QFAQgyTJ4f+yJgUlWIl2V+zzmC4XKAcChcRo2UfWru8NJaP6UlEAo5jLgea9SVXhKadq8Dp3sq3KQbyO37o+D1ZMRUBDky5OOtOf5VFxE9btjdIvgfc0I+OgRwAKjVQHF5qITisuxhQBSO2zveamVAVNsq/hebQxpt6fIHI1lfrHXD0FmM/hHWrHsE88l+PD4E4KACswfjTAkjCCrKdt/OILRSlI83Sy8gaXj/o5gJAMw0/GlOl3b3zL/SP5c3spPtzH11BeM5doMX3elxNgJdvejFTU/7CkNGMun3GsRCTW2NlCScj+nW+NZz1lf88fMpTEVzvvaKYEwyePWxx+Ffrf0NyN4X71K/5GKq4v0nIr3ish2+ceaZNa8jvOB5kMfiw/pNwgLkEalTaxNDpTzLMWlGmnQ=
  file: learn-go
  on:
    repo: yangchuang123456/learn-go
    branch: dev
