language: go
go:
  - 1.x

git:
  submodules: false # 不运行 git submodules 命令
before_install: # 安装 makefile 需要的一些包，其实也可以放在 install 阶段，看个人喜好
  #- sudo apt-get update -qq
  #- sudo apt-get install -qq -y make
install: true # 跳过 install 阶段，因为我已经定义了 before_install。其实 go 项目是需要安装依赖的，只是我放到了下面的 make mycli 命令中做
script: make test && make build # 先运行测试，然后编译
deploy:
  provider: releases # 说明这个阶段要操作 repo 的 releases 页面
  api_key: # github 登录 token
    secure: <snippet>
  file: learn-go # 可执行文件路径
  skip_cleanup: true # 因为我要上传可执行文件到 release，所以不能自动把这个文件清除
  on: # 只有打 tag 时才运行 deploy 阶段
    tags: true

